### ISSUE TITLE
Certificate pinning failure!

### ISSUE THREAD

**Issue by vinsevl** [VKCOM/vkid-android-sdk#12]
Здравствуйте, 

Попробовал интегрировать sdk. В debug версии все работает. Когда собираю release сборку в логах получаю следующую ошибку: 

Failed code to token exchange api call: Certificate pinning failure!
       Peer certificate chain:
              sha256/QZUwl13E7C6NK763j9hFwJnc/jpvOwPfPACxHW0BIbU=: CN=*.vk.com,O=V Kontakte LLC,L=Saint Petersburg,ST=Saint Petersburg,C=RU
             sha256/KJpedoXG+Rd6IJnYeOJjxUjlaDEDI8K1vCBBgzeJkC4=: CN=GlobalSign ECC OV SSL CA 2018,O=GlobalSign nv-sa,C=BE
             sha256/fg6tdrtoGdwvVFEahDVPboswe53YIFjqbABPAdndpd8=: CN=GlobalSign,O=GlobalSign,OU=GlobalSign ECC Root CA - R5
       Pinned certificates for oauth.vk.com:
             sha256/p+lqTZ1LH3x8myQuyq7TpS5Acm5DkluDFCFB1Xnqc/4=
             sha256/IQBnNBEiFuhj+8x6X8XLgh01V9Ic5/V3IRQLNFFc7v4=
             sha256/K87oWBWM9UZfyddvDfoxL+8lpNyoUB2ptGtn0fv6G2Q=

Смотрю на последней версии 1.3.0

**Comment by diklimchuk** [comment]
Добрый день. Мы знаем про проблему, сейчас находимся в процессе решения

**Comment by diklimchuk** [comment]
Проверьте, пожалуйста, еще раз, проблема должна была решиться

**Comment by vinsevl** [comment]
Спасибо, проблема решена
