### ISSUE TITLE
whats the best way to use vk to support third party login

### ISSUE THREAD

**Issue by mozhimen** [VKCOM/vkid-android-sdk#14]
hi, i have the question is : how can i choose the library between [vkid-android-sdk] and [vk-android-sdk] for third party login. i need a stable ,light api for development. thx.

**Comment by diklimchuk** [comment]
If you only need to login using VK, then vkid-android-sdk is better choice, since it's a light weight implementation

**Comment by mozhimen** [comment]
Your response was very helpful, thx.
