### ISSUE TITLE
why accessToken.expireTime value is -1 ? 

### ISSUE THREAD

**Issue by yangjiantao** [VKCOM/vkid-android-sdk#17]
### Опишите баг

Hi:
I use `vkid.authorize` method to login vk, and i got the 'AccessToken' object , but the method `accessToken.getExpireTime()` return -1 , please tell me why

Is there a way I can refresh the accessToken?

### Вопроизведение

1. vkid = new VKID(this);
2. vkid.authorize(this,vkAuthCallback,new VKIDAuthParams.Builder().build());

### Ожидаемое поведение

no content

### Фактическое поведение

yes

### Используемые модули и их версии

sdk version: com.vk.id:vkid:1.1.0

### Скриншоты

no content

### Смартфон или эмулятор

oneplus 9 , android 13

### Внутренний или внешний сервис

no

### Обновляли ли вы сдк

yes

### Исправлена ли ошибка

no

### Где инициализиурете SDK

VKID

### Версия клиента авторизации

vkid:1.1.0

**Comment by diklimchuk** [comment]
Hello. The value -1 means that token will not expire. 
For now there's no way to refresh token, but support for doing so will be added in release 2.0.

**Comment by yangjiantao** [comment]
> Hello. The value -1 means that token will not expire. For now there's no way to refresh token, but support for doing so will be added in release 2.0.

thank you for reply
