### ISSUE TITLE
Помогите с документацией для java

### ISSUE THREAD

**Issue by edgar-code** [VKCOM/vkid-android-sdk#19]
Не могу найти не где как сделать vk id на java кто знает как можно сделать напишите пожалуйста

**Comment by diklimchuk** [comment]
Приветствую!
Интеграция такая же, как для котлина, все методы должны работать и для джавы, только немного изменится синтаксис. Людей, которые пишут на джаве мало, поэтому семпла и документации по этому нет. Попробуйте интегрировать сдк по обычному гайду, а если будут проблемы пишите сюда, постараюсь оперативно ответить

**Comment by edgar-code** [comment]
А разве если я добавлю код котлина в файл .java он не будет показывать ошибку + я не знаю котлина от слова совсем

**Comment by diklimchuk** [comment]
Все в порядке, классы котлина можно вызывать из джавы так же, как и из котлина. Ситнаксис практически такой же. Если будут проблемы смотрите на подсказти студии о названиях методов и их типах. Опять же, если будут какие-то конкретные вопросы я помогу

**Comment by edgar-code** [comment]
Хорошо спасибо большое @diklimchuk

**Comment by edgar-code** [comment]
> я помогу
 Привет еще раз такой вопрос я решил делать через vk-android-sdk нашел часть докоментации на java все сделал все работает топ когда нету приложение вк когда есть надо чтобы кидало туда хз как сделать вот данные
 
> implementation 'com.vk:android-sdk-core:3.3.0'

**Моя функция в MainActivity.java**
`public void onClickAuthVk() {
        VK.login(MainActivity.this, Arrays.asList(VKScope.EMAIL));
    }`
**Мой onActivityResult**
`@Override
    protected void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
        if (data == null || !VK.onActivityResult(requestCode, resultCode, data, new VKAuthCallback() {
            @Override
            public void onLogin(VKAccessToken token) {
                // User passed authorization
            }

            @Override
            public void onLoginFailed(@NonNull VKAuthException e) {

            }
        })) {
            super.onActivityResult(requestCode, resultCode, data);
        }
        super.onActivityResult(requestCode, resultCode, data);
        дальше мой код обработки разрешение..........
}`
Что в приложение без вк
![image](https://github.com/VKCOM/vkid-android-sdk/assets/132489870/70a2c853-182d-4048-8c16-fb1633f36fcc)
Что в приложение когда есть приложении вк

![image](https://github.com/VKCOM/vkid-android-sdk/assets/132489870/95ee682f-156d-4410-901e-a3ad4d6d5fdc)

а вот что по идеи должно быть
но нету
![image](https://github.com/VKCOM/vkid-android-sdk/assets/132489870/7a53b651-65a6-4a21-ae11-4ed1ff536b29)
надеюсь поможешь буду благодарен @diklimchuk

**Comment by edgar-code** [comment]
> > я помогу
 Привет еще раз такой вопрос я решил делать через vk-android-sdk нашел часть докоментации на java все сделал все работает топ когда нету приложение вк когда есть надо чтобы кидало туда хз как сделать вот данные

> > implementation 'com.vk:android-sdk-core:3.3.0'

 **Моя функция в MainActivity.java** `public void onClickAuthVk() { VK.login(MainActivity.this, Arrays.asList(VKScope.EMAIL)); }` **Мой onActivityResult** `@Override protected void onActivityResult(int requestCode, int resultCode, @nullable Intent data) { if (data == null || !VK.onActivityResult(requestCode, resultCode, data, new VKAuthCallback() { @OverRide public void onLogin(VKAccessToken token) { // User passed authorization }

 ```
         @Override
         public void onLoginFailed(@NonNull VKAuthException e) {
 
         }
     })) {
         super.onActivityResult(requestCode, resultCode, data);
     }
     super.onActivityResult(requestCode, resultCode, data);
     дальше мой код обработки разрешение..........
 ```
 
 }` Что в приложение без вк ![image](https://private-user-images.githubusercontent.com/132489870/318427662-70a2c853-182d-4048-8c16-fb1633f36fcc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NzQxNDQsIm5iZiI6MTcxMTk3Mzg0NCwicGF0aCI6Ii8xMzI0ODk4NzAvMzE4NDI3NjYyLTcwYTJjODUzLTE4MmQtNDA0OC04YzE2LWZiMTYzM2YzNmZjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQxMjE3MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYzQwNjE0YzZlZjM3NTYwMjUzZTMxZmRhNDFiY2ExNjBhYjQzNDg4Zjg0OTUzOWU2OTBkYTc4YmI3NDg1MDg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1vII_qzfQdGAosUN1IAIp0aovh-SjSWA2YgF0dIajmg) Что в приложение когда есть приложении вк
 
 ![image](https://private-user-images.githubusercontent.com/132489870/318427833-95ee682f-156d-4410-901e-a3ad4d6d5fdc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NzQxNDQsIm5iZiI6MTcxMTk3Mzg0NCwicGF0aCI6Ii8xMzI0ODk4NzAvMzE4NDI3ODMzLTk1ZWU2ODJmLTE1NmQtNDQxMC05MDFlLWEzYWQ0ZDZkNWZkYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQxMjE3MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iN2I2OTE3YTFhYzk5NzQzYzU3MjkzZDQ5ZTNkM2M2NTdjMjhjNzQ4MWY1MWM5ZGZjNTJhOTgwMTNkNTRkOGIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7KDIR-vMcHjPohcHRvNE-mMjqN4M77KLcHlZnRs8hrk)
 
 а вот что по идеи должно быть но нету ![image](https://private-user-images.githubusercontent.com/132489870/318427973-7a53b651-65a6-4a21-ae11-4ed1ff536b29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NzQxNDQsIm5iZiI6MTcxMTk3Mzg0NCwicGF0aCI6Ii8xMzI0ODk4NzAvMzE4NDI3OTczLTdhNTNiNjUxLTY1YTYtNGEyMS1hZTExLTRlZDFmZjUzNmIyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQxMjE3MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNTFkZWQ2Yzg0N2EwNzg3Y2M1NjA4NjQyZWJhNmQ5YjFhMjBkYTU0NjMxMjgxMzc3OTFjYjkzOTZhYjY4ODdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YgfxJWmbOtACxLKylnqvz-dKlE1mtqxNj8VavIxKmRQ) надеюсь поможешь буду благодарен @diklimchuk

**Comment by edgar-code** [comment]
> > > я помогу
 Привет еще раз такой вопрос я решил делать через vk-android-sdk нашел часть докоментации на java все сделал все работает топ когда нету приложение вк когда есть надо чтобы кидало туда хз как сделать вот данные
> 
> > > implementation 'com.vk:android-sdk-core:3.3.0'
> 
> **Моя функция в MainActivity.java** `public void onClickAuthVk() { VK.login(MainActivity.this, Arrays.asList(VKScope.EMAIL)); }` **Мой onActivityResult** `@Override protected void onActivityResult(int requestCode, int resultCode, @nullable Intent data) { if (data == null || !VK.onActivityResult(requestCode, resultCode, data, new VKAuthCallback() { @OverRide public void onLogin(VKAccessToken token) { // User passed authorization }
> 
> ```
>         @Override
>         public void onLoginFailed(@NonNull VKAuthException e) {
> 
>         }
>     })) {
>         super.onActivityResult(requestCode, resultCode, data);
>     }
>     super.onActivityResult(requestCode, resultCode, data);
>     дальше мой код обработки разрешение..........
> ```
> 
> }` Что в приложение без вк ![image](https://private-user-images.githubusercontent.com/132489870/318427662-70a2c853-182d-4048-8c16-fb1633f36fcc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NzQxNDQsIm5iZiI6MTcxMTk3Mzg0NCwicGF0aCI6Ii8xMzI0ODk4NzAvMzE4NDI3NjYyLTcwYTJjODUzLTE4MmQtNDA0OC04YzE2LWZiMTYzM2YzNmZjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQxMjE3MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYzQwNjE0YzZlZjM3NTYwMjUzZTMxZmRhNDFiY2ExNjBhYjQzNDg4Zjg0OTUzOWU2OTBkYTc4YmI3NDg1MDg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1vII_qzfQdGAosUN1IAIp0aovh-SjSWA2YgF0dIajmg) Что в приложение когда есть приложении вк
> 
> ![image](https://private-user-images.githubusercontent.com/132489870/318427833-95ee682f-156d-4410-901e-a3ad4d6d5fdc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NzQxNDQsIm5iZiI6MTcxMTk3Mzg0NCwicGF0aCI6Ii8xMzI0ODk4NzAvMzE4NDI3ODMzLTk1ZWU2ODJmLTE1NmQtNDQxMC05MDFlLWEzYWQ0ZDZkNWZkYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQxMjE3MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iN2I2OTE3YTFhYzk5NzQzYzU3MjkzZDQ5ZTNkM2M2NTdjMjhjNzQ4MWY1MWM5ZGZjNTJhOTgwMTNkNTRkOGIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7KDIR-vMcHjPohcHRvNE-mMjqN4M77KLcHlZnRs8hrk)
> 
> а вот что по идеи должно быть но нету ![image](https://private-user-images.githubusercontent.com/132489870/318427973-7a53b651-65a6-4a21-ae11-4ed1ff536b29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NzQxNDQsIm5iZiI6MTcxMTk3Mzg0NCwicGF0aCI6Ii8xMzI0ODk4NzAvMzE4NDI3OTczLTdhNTNiNjUxLTY1YTYtNGEyMS1hZTExLTRlZDFmZjUzNmIyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQxMjE3MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNTFkZWQ2Yzg0N2EwNzg3Y2M1NjA4NjQyZWJhNmQ5YjFhMjBkYTU0NjMxMjgxMzc3OTFjYjkzOTZhYjY4ODdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YgfxJWmbOtACxLKylnqvz-dKlE1mtqxNj8VavIxKmRQ) надеюсь поможешь буду благодарен @diklimchuk

**Comment by diklimchuk** [comment]
@edgar-code, это старое сдк, будет прекращаться его поддержка, поэтому лучше писать сразу на этом, чтобы потом все не переписывать. 

По этому вопросу не поддскажу, нужно завести issue в проект старого сдк или написать на почту [devsupport@corp.vk.com](mailto:devsupport@corp.vk.com). По почте относительно быстро отвечают, но не так, как тут. 

Еще раз советую перейти на это сдк, если нужна только авторизация. Потом будет намного проще.

**Comment by edgar-code** [comment]
Я бы с радостью но я даже не знаю что писать ну я сейчас попробую что то сделать и покажу

**Comment by edgar-code** [comment]
android {
    //...
    addManifestPlaceholders(mapOf(
        "VKIDClientID" to "1233445", // ID вашего приложения (app_id).
        "VKIDClientSecret" to "000000000000", // Ваш защищенный ключ (client_secret).
        "VKIDRedirectHost" to "vk.com", // Обычно используется vk.com.
        "VKIDRedirectScheme" to "vk1233445", // Обычно используется vk{ID приложения}.
    ))
} типо вот что это как это написать в build.gradle @diklimchuk

**Comment by edgar-code** [comment]
+ есть приложение matreshka rp они были тоже на java есть их декомпиль и там у них был вк сдк сейчас они на flutter там вроде тоже вк сдк

**Comment by diklimchuk** [comment]
Нужно написать то же самое, только на груви:
```
android {
    defaultConfig {
        addManifestPlaceholders(
                [
                        "VKIDClientID"      : "1233445", // ID вашего приложения (app_id).
                        "VKIDClientSecret"  : "000000000000", // Ваш защищенный ключ (client_secret).
                        "VKIDRedirectHost"  : "vk.com", // Обычно используется vk.com.
                        "VKIDRedirectScheme": "vk1233445", // Обычно используется vk{ID приложения}.
                ]
        )
    }
}
```
В целом все апи такое же, только синтаксис другой

**Comment by diklimchuk** [comment]
> * есть приложение matreshka rp они были тоже на java есть их декомпиль и там у них был вк сдк сейчас они на flutter там вроде тоже вк сдк

Пока что поддержку флаттера не успели сделать, но в ближайшем будуем будет. Недеюсь они перейдут на это сдк

**Comment by edgar-code** [comment]
> "VKIDClientID"      : "1233445", // ID вашего приложения (app_id).
>                         "VKIDClientSecret"  : "000000000000", // Ваш защищенный ключ (client_secret).
>                         "VKIDRedirectHost"  : "vk.com", // Обычно используется vk.com.
>                         "VKIDRedirectScheme": "vk1233445", // Обычно используется vk{ID приложения}.

спс это работает уже

**Comment by edgar-code** [comment]
secrets.properties это надо создать или можно в gradle.properties писать VKIDClientSecret=Ваш защищённый ключ
VKIDClientID=Ваш ID приложения

и куда это девать
maven {
    url("https://artifactory-external.vkpartner.ru/artifactory/vkid-sdk-andorid/")
}

и что вместо это ${sdkVersion}

@diklimchuk

**Comment by diklimchuk** [comment]
1. secrets.properties не нужны, это только для семпла
2. Репозиторий нужно прописать в settings.gradle, синтаксис вот такой:
```
maven {
    url "https://artifactory-external.vkpartner.ru/artifactory/vkid-sdk-andorid/"
}
```
3. в ${sdkVersion} версия сдк, сейчас это "1.3.2"

**Comment by diklimchuk** [comment]
В целом, интеграцию лучше делать не по Readme, а по [докe](https://id.vk.com/about/business/go/docs/ru/vkid/latest/vk-id/intro/plan), там более полная информация и есть примеры использования UI компонентов.

**Comment by edgar-code** [comment]
> 1. secrets.properties не нужны, это только для семпла
> 2. Репозиторий нужно прописать в settings.gradle, синтаксис вот такой:
> 
> ```
> maven {
>     url "https://artifactory-external.vkpartner.ru/artifactory/vkid-sdk-andorid/"
> }
> ```
> 
> 3. в ${sdkVersion} версия сдк, сейчас это "1.3.2"

прекрасно еще раз спасибо а что если у меня это стоит убирать?
repositories {
        google()
        jcenter()
        maven {
            url "https://jitpack.io"
        }
    }или можно не менять?

**Comment by edgar-code** [comment]
+ можешь написать код на java для активации и коллбэка @diklimchuk

**Comment by diklimchuk** [comment]
Правильнее будет все оствить и добавить новую строчку, будет вот так:
```
repositories {
    google()
    jcenter()
    maven {
    url "https://jitpack.io/"
   url "https://artifactory-external.vkpartner.ru/artifactory/vkid-sdk-andorid/"
}
}
```

**Comment by diklimchuk** [comment]
> * можешь написать код на java для активации и коллбэка @diklimchuk

Что именно нужно, активация чего и какой колбек?

**Comment by edgar-code** [comment]
> > * можешь написать код на java для активации и коллбэка @diklimchuk
> 
> Что именно нужно, активация чего и какой колбек?
 ну активацию авторизация и желательно получение Имя и Фамилии

**Comment by edgar-code** [comment]
вот такая фигня 
![image](https://github.com/VKCOM/vkid-android-sdk/assets/132489870/90ec135b-69c9-47bd-9a29-ef98a71d5034)

но когда сделал только второе не было гитхаб репозиториев

**Comment by diklimchuk** [comment]
> > > * можешь написать код на java для активации и коллбэка @diklimchuk
> > 
> > 
> > Что именно нужно, активация чего и какой колбек?
> > ну активацию авторизация и желательно получение Имя и Фамилии

Авторизация через OneTap или обычная, по нажатию на вашу кнопку?

**Comment by edgar-code** [comment]
> > > > * можешь написать код на java для активации и коллбэка @diklimchuk
> > > 
> > > 
> > > Что именно нужно, активация чего и какой колбек?
> > > ну активацию авторизация и желательно получение Имя и Фамилии
> 
> Авторизация через OneTap или обычная, по нажатию на вашу кнопку?

а как лучше но наверное one tap

**Comment by edgar-code** [comment]
2 issues were found when checking AAR metadata:

  1.  Dependency 'com.vk.id:vkid:1.3.2' requires core library desugaring to be enabled
      for :app.

      See https://developer.android.com/studio/write/java8-support.html for more
      details.

  2.  Dependency 'com.vk.id:common:1.3.2' requires core library desugaring to be enabled
      for :app.

      See https://developer.android.com/studio/write/java8-support.html for more
      details.
еще ошибка

**Comment by diklimchuk** [comment]
> вот такая фигня ![image](https://private-user-images.githubusercontent.com/132489870/318449187-90ec135b-69c9-47bd-9a29-ef98a71d5034.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NzkxNzQsIm5iZiI6MTcxMTk3ODg3NCwicGF0aCI6Ii8xMzI0ODk4NzAvMzE4NDQ5MTg3LTkwZWMxMzViLTY5YzktNDdiZC05YTI5LWVmOThhNzFkNTAzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQxMzQxMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YTc4MzQ4MGUwYzkyNmNlODUzYzZjZWQzMTQ4MDFlMTQ4ZjY1YTE2OWM2ZjlhNDQwOWM3ZGYzYTg2ZjA5YWVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TwdWTJTghEoDAfh0U-zazkOJRj66KTfwphNiXIqwHmw)
> 
> но когда сделал только второе не было гитхаб репозиториев

Как я понимаю вылечилось

**Comment by diklimchuk** [comment]
> > > > > * можешь написать код на java для активации и коллбэка @diklimchuk
> > > > 
> > > > 
> > > > Что именно нужно, активация чего и какой колбек?
> > > > ну активацию авторизация и желательно получение Имя и Фамилии
> > 
> > 
> > Авторизация через OneTap или обычная, по нажатию на вашу кнопку?
> 
> а как лучше но наверное one tap

Лучше OneTap, не нужно будет верстать кнопку. Смотрите подробнее в [документации](https://id.vk.com/about/business/go/docs/ru/vkid/latest/vk-id/connection/android/onetap), там все написано, только синтаксис поменйте

**Comment by edgar-code** [comment]
да но у меня требует сделать target 34 а я не могу мой таргет 28 для libGTASA

**Comment by diklimchuk** [comment]
> 2 issues were found when checking AAR metadata:
> 
> 1. Dependency 'com.vk.id:vkid:1.3.2' requires core library desugaring to be enabled
>    for :app.
>    See https://developer.android.com/studio/write/java8-support.html for more
>    details.
> 2. Dependency 'com.vk.id:common:1.3.2' requires core library desugaring to be enabled
>    for :app.
>    See https://developer.android.com/studio/write/java8-support.html for more
>    details.
>    еще ошибка

Вот тут уже отвечал: https://github.com/VKCOM/vkid-android-sdk/issues/18#issuecomment-2018094042

**Comment by diklimchuk** [comment]
> да но у меня требует сделать target 34 а я не могу мой таргет 28 для libGTASA

Такое уже нельзя публиковать в стор, гугл запрещает https://github.com/VKCOM/vkid-android-sdk/issues/19#issuecomment-2029786721

**Comment by edgar-code** [comment]
> > да но у меня требует сделать target 34 а я не могу мой таргет 28 для libGTASA
> 
> Такое уже нельзя публиковать в стор, гугл запрещает https://support.google.com/googleplay/android-developer/thread/239151944/app-must-target-android-13-api-level-33-or-higher?hl=en#:~:text=To%20provide%20users%20with%20a,able%20to%20update%20your%20app.

так а я и не буду

**Comment by edgar-code** [comment]
К сожелению мне vk id не подойдет а если ты не можешь помочь с android vk sdk то я пошел искать другого человека спасибо за помощь

**Comment by diklimchuk** [comment]
> К сожелению мне vk id не подойдет а если ты не можешь помочь с android vk sdk то я пошел искать другого человека спасибо за помощь

Попробуйте написать на почту, которую я присылал, там должны помочь. 
Закрываю issue, переоткройте, если еще будет нужна помощь

**Comment by diklimchuk** [comment]
> да но у меня требует сделать target 34 а я не могу мой таргет 28 для libGTASA

Однако, у меня получилось собрать наш семлп с таргетом 28, попробуйте покопать и понять, в чем проблема
