### ISSUE TITLE
AuthActivity opened with invalid payload json

### ISSUE THREAD

**Issue by nightflav** [VKCOM/vkid-android-sdk#2]
При попытке авторизироваться вылазиет вот эта ошибка. 

AuthActivity opened with invalid payload json

В sample-app тоже, по крайней мере у меня.

**Comment by MaxFix** [comment]
Привет!
А можешь показать json, который тебе пришел?
И/или app_id?

**Comment by MaxFix** [comment]
Какой uri приходит в метод AuthActivity::parseOAuthResult в сэмпле, когда эмулируете?

**Comment by nightflav** [comment]
Id приложения 51805532

сб, 2 дек. 2023 г., 01:53 Maksim ***@***.***>:

**Comment by MaxFix** [comment]
Угу, проблемка известна, фиксим
Для решения в текущий момент, предлагаю создать новое приложение на Self Service :)

**Comment by nightflav** [comment]
А что за Self Service? Можете ссылку какую дать или чего-то такое?

**Comment by Thisman** [comment]
Похожая проблема https://github.com/VKCOM/vkid-android-sdk/issues/4

**Comment by begezavr2** [comment]
> При попытке авторизироваться вылазиет вот эта ошибка.
> 
> AuthActivity opened with invalid payload json
> 
> В sample-app тоже, по крайней мере у меня.

Пофиксили на бэкенде, можете проверить что всё работает?
