### ISSUE TITLE
[BUG]: Два приложения с сдк конфликтуют

### ISSUE THREAD

**Issue by T8RIN** [VKCOM/vkid-android-sdk#27]
### Опишите баг

У меня есть два приложения с onetap sdk, при получении результата на финальном этапе, после нажатия "войти как", мне предлагается выбрать одно из них чтобы обработать результат, так быть не должно, почему оно все не в рамках одного приложения

### Вопроизведение

Сделайте два приложения с onetap sdk

### Ожидаемое поведение

Нет диалога для выбора приложения которое выберет результат

### Фактическое поведение

Есть диалог для выбора приложения которое выберет результат

### Используемые модули и их версии

onetap 1.3.2

### Смартфон или эмулятор

Pixel 8, android 14

### Внутренний или внешний сервис

внутренний

### Обновляли ли вы сдк

нет

### Исправлена ли ошибка

нет

### Где инициализиурете SDK

В onetap кнопке

### Версия клиента авторизации

нет

### Дополнительные заметки

мне кажется что com.vk.id.internal.auth.RedirectUriReceiverActivity должно иметь exported="false"

**Comment by begezavr2** [comment]
У каждого приложения должен быть свой appId, у вас получается он общий на оба приложения, это не правильно. Заведите в кабинете VK ID второе приложение и тогда не будет такого поведения.

**Comment by begezavr2** [comment]
> мне кажется что com.vk.id.internal.auth.RedirectUriReceiverActivity должно иметь exported="false"

Пожалуйста обновитесь на только что вышедшую 1.3.3, там сильно улучшена обработка редирект урла.

**Comment by T8RIN** [comment]
Спасибо, попробую!
