### ISSUE TITLE
How to fix?

### ISSUE THREAD

**Issue by evgenybozhko2** [VKCOM/vkid-android-sdk#3]
java.net.ConnectException: failed to connect to oauth.vk.com/78.137.1.11 (port 443) from /192.168.1.13 (port 45482) after 60000ms: isConnected failed: EHOSTUNREACH (No route to host)
Failed code to token exchange api call

**Comment by begezavr2** [comment]
Тут сложно что-то посоветовать, выглядит как будто у вас нет доступа до oauth.vk.com. Может впн не пускает?
