### ISSUE TITLE
how to use java

### ISSUE THREAD

**Issue by vivian688** [VKCOM/vkid-android-sdk#36]
I just need to access vk id authorization，and the version I accessed is 2.1.0:
implementation 'com.vk.id:vk-sdk-support:2.1.0'

How to call a method through java code？

![20240816170922](https://github.com/user-attachments/assets/e6aa2b0f-97e6-48ca-b088-cdf5ab8e5d57)
![20240816170958](https://github.com/user-attachments/assets/5eea42d2-412a-4574-9bac-8144a948c2b9)
![20240816171042](https://github.com/user-attachments/assets/bdd912c8-8200-4b68-ba5f-d0fc37b6659b)

I would be grateful if you could give me some Java code examples.

**Comment by diklimchuk** [comment]
Hi!
Here's an example of calling authorize:
```
public class Tmp extends AppCompatActivity {
    @Override
    public void onCreate(@Nullable Bundle savedInstanceState, @Nullable PersistableBundle persistentState) {
        super.onCreate(savedInstanceState, persistentState);
        VKID.Companion.getInstance().authorize(this, new VKIDAuthCallback() {
            @Override
            public void onAuth(@NonNull AccessToken accessToken) {

            }

            @Override
            public void onFail(@NonNull VKIDAuthFail fail) {

            }

            @Override
            public void onAuthCode(@NonNull AuthCodeData data, boolean isCompletion) {
            }
        }, new VKIDAuthParams.Builder().build());
    }
}
```
Please let me know if you need any other code samples.

**Comment by vivian688** [comment]
> Hi! Here's an example of calling authorize:
> 
> ```
> public class Tmp extends AppCompatActivity {
>     @Override
>     public void onCreate(@Nullable Bundle savedInstanceState, @Nullable PersistableBundle persistentState) {
>         super.onCreate(savedInstanceState, persistentState);
>         VKID.Companion.getInstance().authorize(this, new VKIDAuthCallback() {
>             @Override
>             public void onAuth(@NonNull AccessToken accessToken) {
> 
>             }
> 
>             @Override
>             public void onFail(@NonNull VKIDAuthFail fail) {
> 
>             }
> 
>             @Override
>             public void onAuthCode(@NonNull AuthCodeData data, boolean isCompletion) {
>             }
>         }, new VKIDAuthParams.Builder().build());
>     }
> }
> ```
> 
> Please let me know if you need any other code samples.

thanks
