### ISSUE TITLE
Getting access token from the backend

### ISSUE THREAD

**Issue by sushencev-apron** [VKCOM/vkid-android-sdk#39]
This issue was created by mistake. Please delete :)

**Comment by diklimchuk** [comment]
Hello!
You can folow the [guide](https://id.vk.com/about/business/go/docs/en/vkid/latest/vk-id/connection/setting-up-auth/setup-android) for reciving the token on backend. In short you need to do this:
- Set up OneTap
- Pass codeChallenge to authParams
- Override onAuthCode method
- After receving auth code and deviceId send them to backend
- Exchange code and deviceid for access token
