### ISSUE TITLE
Ошибка при исползовании vk id sdk

### ISSUE THREAD

**Issue by corporal777** [VKCOM/vkid-android-sdk#4]
Здравствуйте. Использую sdk 'com.vk.id:vkid:1.0.0' 
Все ключи прописал, 
manifestPlaceholders = [
                VKIDRedirectHost : "vk.com",
                VKIDRedirectScheme : "vk------",
                VKIDClientID : "--------",
                VKIDClientSecret : "---------------"
        ]
но получаю ошибку 401 Failed code to token exchange api call

**Comment by corporal777** [comment]
Хорошо, secret client я посмотрю
Но теперь начала приходить другая ошибка
AuthActivity opened with invalid payload json
до этого я пробовал использовать старую сдк и она работала, потом вернул vk id sdk

**Comment by begezavr2** [comment]
> Хорошо, secret client я посмотрю Но теперь начала приходить другая ошибка AuthActivity opened with invalid payload json до этого я пробовал использовать старую сдк и она работала, потом вернул vk id sdk

Это уже похоже на другую известную проблему с миграцией старых приложений, над фиксом уже работаем. Пока попробуйте создать новое приложение здесь https://id.vk.com/about/business/go и с его данными потестируйте сдк.

**Comment by corporal777** [comment]
> > Хорошо, secret client я посмотрю Но теперь начала приходить другая ошибка AuthActivity opened with invalid payload json до этого я пробовал использовать старую сдк и она работала, потом вернул vk id sdk
> 
> Это уже похоже на другую известную проблему с миграцией старых приложений, над фиксом уже работаем. Пока попробуйте создать новое приложение здесь https://id.vk.com/about/business/go и с его данными потестируйте сдк.

Приложение мы недавно создали, 1-2 дня прошло

**Comment by corporal777** [comment]
> Проверьте ещё раз что VKIDClientSecret указали верный. Если всё-равно не заработает, напишите полностью ошибку пожалуйста, как-то так можно посмотреть:
> 
> ```kotlin
> override fun onFail(fail: VKIDAuthFail) {
>     val error = fail as VKIDAuthFail.FailedApiCall
>     Log.d("xxx", error.throwable.message)
>     // ...
> }
> ```

error.throwable.message -> AuthActivity opened with invalid payload json
Приложение создано новое
В данный момент работает только этот sdk -> 'com.vk:androidsdk:1.6.9'
Пробовали этот sdk -> 'com.vk:android-sdk-core:4.1.0' , но приходит ошибка "sdk options is undefined"

**Comment by begezavr2** [comment]
> > Проверьте ещё раз что VKIDClientSecret указали верный. Если всё-равно не заработает, напишите полностью ошибку пожалуйста, как-то так можно посмотреть:
> > ```kotlin
> > override fun onFail(fail: VKIDAuthFail) {
> >     val error = fail as VKIDAuthFail.FailedApiCall
> >     Log.d("xxx", error.throwable.message)
> >     // ...
> > }
> > ```
> 
> error.throwable.message -> AuthActivity opened with invalid payload json Приложение создано новое В данный момент работает только этот sdk -> 'com.vk:androidsdk:1.6.9' Пробовали этот sdk -> 'com.vk:android-sdk-core:4.1.0' , но приходит ошибка "sdk options is undefined"

Проблема проявляется если использовать новое и старое сдк одновременно или по очереди, у вас ошибка invalid payload json даже если создали новое приложение и использовали только com.vk.id:vkid:1.0.0?

**Comment by corporal777** [comment]
> > > Проверьте ещё раз что VKIDClientSecret указали верный. Если всё-равно не заработает, напишите полностью ошибку пожалуйста, как-то так можно посмотреть:
> > > ```kotlin
> > > override fun onFail(fail: VKIDAuthFail) {
> > >     val error = fail as VKIDAuthFail.FailedApiCall
> > >     Log.d("xxx", error.throwable.message)
> > >     // ...
> > > }
> > > ```
> > 
> > error.throwable.message -> AuthActivity opened with invalid payload json Приложение создано новое В данный момент работает только этот sdk -> 'com.vk:androidsdk:1.6.9' Пробовали этот sdk -> 'com.vk:android-sdk-core:4.1.0' , но приходит ошибка "sdk options is undefined"
> 
> Проблема проявляется если использовать новое и старое сдк одновременно или по очереди, у вас ошибка invalid payload json даже если создали новое приложение и использовали его только с com.vk.id:vkid:1.0.0?

Мы создали новое приложение
Потом испоьзовали его с com.vk.id:vkid:1.0.0, но приходила ошибка

**Comment by begezavr2** [comment]
Да, у нас есть такая проблема, сейчас её решаем - что если вы используете на одном и том же app id сначала старое сдк а потом новое, то новое перестает работать, это про ошибку invalid payload json.

Для того чтобы разобраться в чем дело в случае Failed code to token exchange api call пришлите описание из error.throwable.message,  "Failed code to token exchange api call" это error.description и в нем недостаточно информации, нужен именно error.throwable

**Comment by Levin-nik** [comment]
> Да, у нас есть такая проблема, сейчас её решаем - что если вы используете на одном и том же app id сначала старое сдк а потом новое, то новое перестает работать, это про ошибку invalid payload json.
> 
> Для того чтобы разобраться в чем дело в случае Failed code to token exchange api call пришлите описание из error.throwable.message, "Failed code to token exchange api call" это error.description и в нем недостаточно информации, нужен именно error.throwable

Здравствуйте, словили ошибку `invalid payload json`, но не трогали app id на старых версиях sdk, ждать обновлений или есть решение этой проблемы?

**Comment by begezavr2** [comment]
> > Да, у нас есть такая проблема, сейчас её решаем - что если вы используете на одном и том же app id сначала старое сдк а потом новое, то новое перестает работать, это про ошибку invalid payload json.
> > Для того чтобы разобраться в чем дело в случае Failed code to token exchange api call пришлите описание из error.throwable.message, "Failed code to token exchange api call" это error.description и в нем недостаточно информации, нужен именно error.throwable
> 
> Здравствуйте, словили ошибку `invalid payload json`, но не трогали app id на старых версиях sdk, ждать обновлений или есть решение этой проблемы?

Разбираемся, проблема на бэкенде, поэтому обновления сдк скорей всего не потребуется. Обходных решений пока тоже не можем предложить, к сожалению.

**Comment by begezavr2** [comment]
> > Да, у нас есть такая проблема, сейчас её решаем - что если вы используете на одном и том же app id сначала старое сдк а потом новое, то новое перестает работать, это про ошибку invalid payload json.
> > Для того чтобы разобраться в чем дело в случае Failed code to token exchange api call пришлите описание из error.throwable.message, "Failed code to token exchange api call" это error.description и в нем недостаточно информации, нужен именно error.throwable
> 
> Здравствуйте, словили ошибку `invalid payload json`, но не трогали app id на старых версиях sdk, ждать обновлений или есть решение этой проблемы?

Пофиксили на бэкенде, можете проверить что всё работает?
