### ISSUE TITLE
[DOC]: token sign

### ISSUE THREAD

**Issue by pavelkormilicin** [VKCOM/vkid-android-sdk#42]
### Описание

В документации указано, что ID-токен подписан  при помощи алгоритома HS256 https://id.vk.com/about/business/go/docs/en/vkid/latest/vk-id/connection/tokens/id-token

Однако при авторизации мы получаем токены, подписанные алгоритмом RS256 
Для проверки подписи в таком случае помимо приватного ключа(который доступен в лк), необходим и публичный ключ. 

Где взять публичный ключ? Как верифицировать токен? 
<img width="619" alt="Screenshot at Nov 05 01-01-04" src="https://github.com/user-attachments/assets/63ad3111-44e1-40a1-9ce4-79f96f505c55">
<img width="483" alt="Screenshot at Nov 05 01-01-25" src="https://github.com/user-attachments/assets/6f2fefd2-d045-48f9-98c6-3f2822a9bff6">

**Comment by diklimchuk** [comment]
Спасибо, это ошибка в документации. Уточню возможность получения публичного ключа и вернусь с ответом

**Comment by diklimchuk** [comment]
@pavelkormilicin, обновим документацию, если вам срочно нужен публичный ключ, то вот он:
```
-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAvsvJlhFX9Ju/pvCz1frB
DgJs592VjdwQuRAmnlJAItyHkoiDIOEocPzgcUBTbDf1plDcTyO2RCkUt0pz0WK6
6HNhpJyIfARjaWHeUlv4TpuHXAJJsBKklkU2gf1cjID+40sWWYjtq5dAkXnSJUVA
UR+sq0lJ7GmTdJtAr8hzESqGEcSP15PTs7VUdHZ1nkC2XgkuR8KmKAUb388ji1Q4
n02rJNOPQgd9r0ac4N2v/yTAFPXumO78N25bpcuWf5vcL9e8THk/U2zt7wf+aAWL
748e0pREqNluTBJNZfmhC79Xx6GHtwqHyyduiqfPmejmiujNM/rqnA4e30Tg86Yn
cNZ6vLJyF72Eva1wXchukH/aLispbY+EqNPxxn4zzCWaLKHG87gaCxpVv9Tm0jSD
2es22NjrUbtb+2pAGnXbyDp2eGUqw0RrTQFZqt/VcmmSCE45FlcZMT28otrwG1ZB
kZAb5Js3wLEch3ZfYL8sjhyNRPBmJBrAvzrd8qa3rdUjkC9sKyjGAaHu2MNmFl1Y
JFQ3J54tGpkGgJjD7Kz3w0K6OiPDlVCNQN5sqXm24fCw85Pbi8SJiaLTp/CImrs1
Z3nHW5q8hljA7OGmqfOP0nZS/5zW9GHPyepsI1rW6CympYLJ15WeNzePxYS5KEX9
EncmkSD9b45ge95hJeJZteUCAwEAAQ==
-----END PUBLIC KEY-----
```

**Comment by diklimchuk** [comment]
Я закрываю issue, переоткройте если появятся еще вопросы
