### ISSUE TITLE
Невозможно сменить аккаунт

### ISSUE THREAD

**Issue by XJIOP** [VKCOM/vkid-android-sdk#46]
### Описание

Как войти под другим аккаунтом? 

При вызове
`VKID.Companion.getInstance().authorize` 
используя свою кнопку авторизации, каждый раз заходит в один и тот же аккаунт, без возможости выбора или войти в другой аккаунт. 

Логаут не помогает
`VKID.Companion.getInstance().logout `

Даже очистка данных приложения не помогает, все равно заходит в один и тот же аккаунт.

**Comment by diklimchuk** [comment]
По умолчанию происходит авторизация в текущем аккаунте. Чтобы запустить смену аккаунта нужно передать Prompt.LOGIN:
```
VKID.instance.authorize(params = VKIDAuthParams { prompt = Prompt.LOGIN })
```
Учтите, что смена аккаунта запускается в Chrome Custom Tabs

**Comment by XJIOP** [comment]
Понял спасибо!

А как сделать полный выход, что бы без параметра Prompt.LOGIN была возможность логина? Было бы неплохо добавить в VKIDLogoutParams дополнительный параметр для полного выхода.
