### ISSUE TITLE
tell me how to use java

### ISSUE THREAD

**Issue by DSIhjp** [VKCOM/vkid-android-sdk#6]

**Comment by diklimchuk** [comment]
Please clarify your question. In what way it relates to VK ID SDK?

**Comment by DSIhjp** [comment]
I want user VK ID SDK ,from java ,I do not  kotlin

**Comment by diklimchuk** [comment]
The code should be very similiar, the only difference would be java syntax instead of kotlin. If you can't do that yourself, you can tell what parts of sdk you will be using (plain auth, onetap, etc) and i will provide you with necessary code

**Comment by DSIhjp** [comment]
plain auth

**Comment by diklimchuk** [comment]
There is a method in VKID class that doesn't use coroutines: 
```
vkid.authorize(this@MainActivity, vkAuthCallback)
```
The first parameter is the LifecycleOwner, for example an Actviity and the second one is the implementation of VKID.AuthCallback interface

**Comment by diklimchuk** [comment]
I will close this issue, since it seems that the question. Feel free to reopen this, if you need any further help
