### ISSUE TITLE
Email из VkAuthCallback идентичен accessToken

### ISSUE THREAD

**Issue by PavelIsProgrammer** [VKCOM/vkid-android-sdk#7]
При успешной авторизации через библиотеку com.vk.id:vkid:1.1.0 в VkAuthCallback в методе onSuccess accessToken.email приходит точно такой же как и сам accessToken

**Comment by diklimchuk** [comment]
Подскажите, в каком конкретно поле проверяете email? Он должен быть в AccessToken.userData.email

**Comment by PavelIsProgrammer** [comment]
Из этого поля и беру email

Вот залоганные данные: {"access_token":"vk1.a.oIevHiQXCMfidoakZk58Ik7s4cNAmSb87r7IniNLecGi-_Ioqgz5sjp7wh3U0kcTW5VI4UindWh-Cw98FLZguvvyZtdaWYAjhIjSUI-E74bSyHuLuGxL8T2eG48k2nBCtl30mAqEF74GlH8ALixStlFdzsHwRsjdzgzjT2_46mB_q7mduI4QLHecJhtkYcix57Xe93MWm3Sq_78Bo9o-1g","email":"vk1.a.oIevHiQXCMfidoakZk58Ik7s4cNAmSb87r7IniNLecGi-_Ioqgz5sjp7wh3U0kcTW5VI4UindWh-Cw98FLZguvvyZtdaWYAjhIjSUI-E74bSyHuLuGxL8T2eG48k2nBCtl30mAqEF74GlH8ALixStlFdzsHwRsjdzgzjT2_46mB_q7mduI4QLHecJhtkYcix57Xe93MWm3Sq_78Bo9o-1g","first_name":"Павел","last_name":"П.","phone":"+7911*******"}

**Comment by diklimchuk** [comment]
Пожалуйста, отредактуйте сообщение и уберите значение access_token, иначе ваш аккаунт могут взломать!

**Comment by PavelIsProgrammer** [comment]
Блин, по третьему кругу пошел проверять и увидел, что и правда брал данные не оттуда. Извините пожалуйста за беспокойство, спасибо большое, что помогли найти решение)
