### ISSUE TITLE
Не работает авторизация 401 invalid_client

### ISSUE THREAD

**Issue by evgeny5454** [VKCOM/vkid-android-sdk#9]
Повторно зарегистрировали приложение в VKID 
в результате авторизации ошибка Failed code to token exchange api call: Api error: 401 {"error":"invalid_client","error_description":"client_secret is incorrect"}

VKIDClientSecret проверил, корректный 

Есть решение?

**Comment by evgeny5454** [comment]
пробовал 1.1.0 и 1.2.0 версии

**Comment by evgeny5454** [comment]
Старая версия sdk с обновленными id и секретным ключом тоже не работает

**Comment by begezavr2** [comment]
> Повторно зарегистрировали приложение в VKID в результате авторизации ошибка Failed code to token exchange api call: Api error: 401 {"error":"invalid_client","error_description":"client_secret is incorrect"}
> 
> VKIDClientSecret проверил, корректный
> 
> Есть решение?

Попробуйте авторизоваться со своими данными [в сэмпле](https://github.com/VKCOM/vkid-android-sdk/tree/master/sample/app). Если сэмпл уже устанавливали, то сначала удалите или очистите данные, чтобы исключить кэширование.

**Comment by evgeny5454** [comment]
В семпле та же ошибка
![photo_2024-02-02 09 40 56](https://github.com/VKCOM/vkid-android-sdk/assets/57985422/e7de68c2-db80-4fa1-b65f-830cad8ff93c)
